server:
  port: 4001

spring:
  cloud:
    alicloud:
      access-key: LTAI5t6VaLmeM6FdE7mRC8xg
      secret-key: aBpCYYUhLDoCnDjxUryCVhvSQPM11f
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-kee
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        method: POST
        appcode: fc9a11c89fee4b3cb12b217e6c461ed0
        tpl-id: TP1711063


